### ISSUE TITLE
Display link to Etherscan as the transaction is confirming / confirmed.

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#22]
1. As the transaction is confirming - display link to Etherscan and "confirming"

2. As the transaction is confirmed - display link to Etherscan and "confirmed"

**Comment by marsrobertson** [comment]
Noticed that usually we refresh pages automatically.

Here is something new I've observed:

![image](https://user-images.githubusercontent.com/44369284/56420927-06ca8f00-6298-11e9-969d-f0a2cc1055eb.png)

We should be consistent + link to Etherscan

**Comment by satello** [comment]
This should be left up to the wallet. On most DApps once you send a transaction it either has a waiting screen like this or just continues on and tells you to wait for your tx to be mined. The user can use MetaMask etc. to go to the pending tx on Etherscan.

Page will refresh automatically I will remove this warning.
