### ISSUE TITLE
Better communicate to the user the privacy implications of the blockchain - can anyone see the transaction? (getting a strange error)

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#28]
First thought: everything is public on the blockchain. Need to communicate to the users about the privacy implications.

So then I visited the link as a random MetaMask user.

Getting an error:

```
Error: Couldn't decode bytes from ABI: 0x
    at o.formatOutputDynamicBytes [as _outputFormatter] (formatters.js:242)
    at type.js:258
    at o.decode (type.js:250)
    at index.js:330
    at Array.forEach (<anonymous>)
    at m.decodeParameters (index.js:329)
    at M.p._decodeMethodReturn (index.js:416)
    at l.outputFormatter (index.js:740)
    at l.formatOutput (index.js:167)
    at o (index.js:444)
```

![image](https://user-images.githubusercontent.com/44369284/56424321-a6434e00-62a7-11e9-8a7b-07967a1f6c67.png)

**Comment by satello** [comment]
I am unable to reproduce this. Can you give me the transactionID that failed for you? (The hash at the end of the URI)

**Comment by marsrobertson** [comment]
My bad.

I was on the wrong network, nothing to do with privacy.

https://escrow.kleros.io/contract/0xd64168d1cc10f2349a7095c0a8ec9c4d1c80e0d8/transaction/12

* Mainnet: error
* Kovan: displays correctly

In the production it will be mainnet only.

So if you cannot read the transaction, display some warning: _"transaction not found, double check the URL and ensure you are on the right network"_

-----

Education to the users about privacy implications - the point remains valid. If you have original agreements and put some access credentials / secret URL / anything confidential - you may want to exercise extra caution.
