### ISSUE TITLE
Use the pattern 1. approve 2. transact as opposed to two simultaneous transaction with 2nd fail warning in Metamask UI

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#65]
My recent tweet about 1. approve 2. transact pattern: https://twitter.com/marsxrobertson/status/1212856982933250059

![2 transactions](https://user-images.githubusercontent.com/44369284/71880484-5ef83880-3128-11ea-8ee7-36b71daa57f0.gif)

It's similar to #63

I genuinely think that:
1. approve
2. transact 

Is way much better...

I'm kind of an advanced user, I know that Metamask runs the transaction "as if" to estimate the gas cost, that's why it knows the token hasn't been approved (1st transaction) that's why showing in the UI that 2nd transaction is failing.

That's terrible usability.

**Comment by satello** [comment]
It should be doing approve first you are correct. This is either a race condition and/or a bug.

**Comment by satello** [comment]
And while this is bad usability I believe it would be worse to wait for the Approve transaction to mine before asking for the transaction signature to avoid the error message in MetaMask. A regular user will not understand that they need to wait around to sign another transaction, so that is why I think we need to get the two signatures right away.

**Comment by marsrobertson** [comment]
Who is our audience?

Technical guys...

Technical, early adopters, someone who knows what gas and ERC-20 is...

I think it is OK to explain:

> in order to create Escrow, first we need to unlock your token
> this is part of ERC-20 standard (approve)
> while there is an extension ERC-223 that does approveAndCall
> ...
> BLAH BLAH BLAH knowledge base content marketing

Using less words, screenshot from Uniswap:
![image](https://user-images.githubusercontent.com/44369284/71915215-2fbae900-3173-11ea-84d2-3989113a71fa.png)

**Comment by marsrobertson** [comment]
Another pattern, via Gitcoin: https://gitcoin.co/grants/315/trackato-defi/fund

![image](https://user-images.githubusercontent.com/44369284/72278540-25459700-362c-11ea-8e65-163b8c036368.png)

**Comment by marsrobertson** [comment]
From Aragon:

![image](https://user-images.githubusercontent.com/44369284/73541652-e9cc0a80-442a-11ea-8cf7-ae19126e6067.png)
