### ISSUE TITLE
Quick Wins for the First Release

### ISSUE THREAD

**Issue by epiqueras** [kleros/escrow#7]
The icon looks strange there. It is also unnecessary if we already have the button on the nav bar. We can follow Plinio's design or a quicker solution would be to have some text saying "You don't have any transactions yet, \<create some\>."
<img width="1325" alt="screen shot 2019-01-17 at 1 35 57 pm" src="https://user-images.githubusercontent.com/19157096/51323010-f6b7cf00-1a5e-11e9-8977-f613af42f61b.png">

No need for a plus icon there. You are not adding notifications.
<img width="238" alt="screen shot 2019-01-17 at 1 36 52 pm" src="https://user-images.githubusercontent.com/19157096/51323011-f7506580-1a5e-11e9-82f1-f44cfa686966.png">

Capitalize email.
<img width="480" alt="screen shot 2019-01-17 at 1 36 58 pm" src="https://user-images.githubusercontent.com/19157096/51323012-f7506580-1a5e-11e9-9cdf-cb1ef96b26ca.png">

Fix the font here.
<img width="294" alt="screen shot 2019-01-17 at 1 37 20 pm" src="https://user-images.githubusercontent.com/19157096/51323013-f7506580-1a5e-11e9-9a13-0920b59e8e60.png">

Use our IPFS node for hosting and displaying files otherwise they will never load.
<img width="889" alt="screen shot 2019-01-17 at 1 38 06 pm" src="https://user-images.githubusercontent.com/19157096/51323014-f7506580-1a5e-11e9-8e16-3dbee26d7671.png">

Add copy to clipboard.
<img width="913" alt="screen shot 2019-01-17 at 1 38 23 pm" src="https://user-images.githubusercontent.com/19157096/51323015-f7e8fc00-1a5e-11e9-85ae-6026624fa554.png">

This is not working.
<img width="167" alt="screen shot 2019-01-17 at 1 38 27 pm" src="https://user-images.githubusercontent.com/19157096/51323016-f7e8fc00-1a5e-11e9-9298-23a7de40d37d.png">

"Summary"
<img width="97" alt="screen shot 2019-01-17 at 1 38 37 pm" src="https://user-images.githubusercontent.com/19157096/51323017-f7e8fc00-1a5e-11e9-9f98-a8aea03fa7a6.png">

Nothing happens after paying and if I pay again the transaction reverts (expected).
<img width="307" alt="screen shot 2019-01-17 at 1 50 52 pm" src="https://user-images.githubusercontent.com/19157096/51323018-f8819280-1a5e-11e9-80f5-ca09783b448a.png">

**Comment by n1c01a5** [comment]
done

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/56392285-f0d1b580-6228-11e9-898d-9c77308cfb96.png)

Make placeholder looks more like a placeholder.

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/56392988-eadcd400-622a-11e9-9c60-e00ea727cddb.png)

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/56393151-6f2f5700-622b-11e9-8d35-4789542c519c.png)

**Comment by marsrobertson** [comment]
Rounding to 3 decimal points. (easy first issue)

![image](https://user-images.githubusercontent.com/44369284/56394420-38f3d680-622f-11e9-90f3-c5083ae8fba4.png)

**Comment by marsrobertson** [comment]
Weird alignment

![image](https://user-images.githubusercontent.com/44369284/56417478-fdd3c080-628b-11e9-85e1-0f6971e76d7a.png)

**Comment by marsrobertson** [comment]
# There is only one option

So remove the dropdown, keep default as default.

![image](https://user-images.githubusercontent.com/44369284/56420010-3a0b1f00-6294-11e9-94d6-233a8112e2fc.png)
