### ISSUE TITLE
MetaEvidence Token information does not match token in the contract?

### ISSUE THREAD

**Issue by marsrobertson** [kleros/escrow#70]
Kovan:

* https://escrow.kleros.io/
* https://escrow.kleros.io/contract/0xfe4fd3f2d4470fd032ee3e961a981b08e254a0d7/payment/0

```
backend.js:6 Error: MetaEvidence Token information does not match token in the contract
    at main.e9a07078.chunk.js:1
    at v (1.93be02ba.chunk.js:1)
    at Generator._invoke (1.93be02ba.chunk.js:1)
    at Generator.e.<computed> [as next] (1.93be02ba.chunk.js:1)
    at L (1.93be02ba.chunk.js:1)
    at T (1.93be02ba.chunk.js:1)
```

Created escrow for `0.000000000000000002` of a newly created token: https://kovan.etherscan.io/tx/0xf49fc9b327146071092f10b00f024aeaee68547fbb185abcfdfe62f3c818a1b8

**Comment by satello** [comment]
Can you add the source code of the token contract on Etherscan?

**Comment by marsrobertson** [comment]
Here you go: https://kovan.etherscan.io/address/0x0ca79ecc9bba3897a4b1bee7a554988c61eb4a41#code

**PNK DAI amalgam** created when deploying the contract:

https://github.com/marsrobertson/hourly-rate/blob/master/contracts/HourlyRate.sol#L70-L74

FYI: https://abi.hashex.org/ - handy tool for ABI-encoding constructor parameters.

**Comment by satello** [comment]
@marsrobertson The test escrow should now appear. Thanks for reporting
